// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbOvm3Bg_b2klQ8zskr5fNVmlfCad_pTI',
    appId: '1:448859682139:web:9231a16b16eed00a70567e',
    messagingSenderId: '448859682139',
    projectId: 'new-app-fad18',
    authDomain: 'new-app-fad18.firebaseapp.com',
    storageBucket: 'new-app-fad18.firebasestorage.app',
    measurementId: 'G-EGJGDC9V8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7xsCIKRlasGXeUJl9CMm9YWo0498_cvo',
    appId: '1:448859682139:android:4c35a1985f6ff51770567e',
    messagingSenderId: '448859682139',
    projectId: 'new-app-fad18',
    storageBucket: 'new-app-fad18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3SwGZ33ZtJzFlXPDfM9gF0gVM6jlzI8E',
    appId: '1:448859682139:ios:ba943beb3409368470567e',
    messagingSenderId: '448859682139',
    projectId: 'new-app-fad18',
    storageBucket: 'new-app-fad18.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3SwGZ33ZtJzFlXPDfM9gF0gVM6jlzI8E',
    appId: '1:448859682139:ios:ba943beb3409368470567e',
    messagingSenderId: '448859682139',
    projectId: 'new-app-fad18',
    storageBucket: 'new-app-fad18.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbOvm3Bg_b2klQ8zskr5fNVmlfCad_pTI',
    appId: '1:448859682139:web:05121b483a27acea70567e',
    messagingSenderId: '448859682139',
    projectId: 'new-app-fad18',
    authDomain: 'new-app-fad18.firebaseapp.com',
    storageBucket: 'new-app-fad18.firebasestorage.app',
    measurementId: 'G-FP58VZFGZG',
  );
}
